name: Inferencing-Client
proc_type: inferencing
is_active: True
is_sequential: True

config:
  services: ["bot"]
  extraArgs:
    model_name: "Xception"
    serving_image: "tensorflow/serving"
    chromedriver: "/home/ajkdrag/Downloads/programs/chromedriver_linux64/chromedriver"
    bot_url: "https://gearoid.me/pokemon/"
    max_inferences: 8
    num_attempts: 4
    dex: "data/dex.csv"
    export: "export"
 
