name: Base-Pipeline
proc_type: pipeline
is_active: True
is_sequential: True

subprocesses:
  # - config_path: configs/processes/scraping.cfg.yaml
  # - config_path: configs/processes/preprocessing.cfg.yaml
  - config_path: configs/processes/training.cfg.yaml
  # - config_path: configs/processes/inferencing.cfg.yaml
