name: Image-Preprocessor
proc_type: preprocessing 
is_active: True
is_sequential: True

config:
  preprocessors: ["augmentation"]
  extraArgs:
    num_aug_images: 25
    in_dir: "data/images/raw/"
    processed_dir: "data/images/preprocessed/"
    augmented_dir: "data/images/augmented_2/"
